version: '3'
services:
  postgres:
    image: postgis:3.1.4-14-bullseye
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: traffic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smarttraffic
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
    pgdata: