version: '3'
services:
  postgres:
    image: postgres:14
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      -./ddl-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: traffic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
    pgdata:
